include	../../Makefile.options

CFLAGS += -Wno-unused -g -frounding-math -Duse_namespace
PKG_CONFIG +=  `pkg-config --cflags playercore` `pkg-config --libs playercore`
OBJ = obj/
SRC = src/

OBJS = $(OBJ)Logger.o $(OBJ)ICP.o $(OBJ)Bsp.o $(OBJ)Raytracer.o $(OBJ)CameraParameters.o $(OBJ)PMDLocalizationDriver.o $(OBJ)RaytracerDriver.so

all: $(OBJ) $(OBJ)libPMDlocalize.so $(OBJ)libRaytracerDriver.so

install: $(OBJ)libPMDlocalize.so $(OBJ)libRaytracerDriver.so
	@$(ECHO) -y "[LIB] Installing PMD Localize Library into $(INSTALLDIR)lib/"
	@cp $(OBJ)libPMDlocalize.so $(INSTALLDIR)lib/libPMDlocalize.so
	@$(ECHO) -y "[LIB] Installing Raytracer Driver into $(INSTALLDIR)lib/"
	@cp $(OBJ)libRaytracerDriver.so $(INSTALLDIR)lib/libRaytracerDriver.so

uninstall: 
	@$(ECHO) -r "[REM] Uninstalling libPMDlocalize.so from $(INSTALLDIR)lib/"
	@rm -f $(INSTALLDIR)lib/libPMDlocalize.so
	@$(ECHO) -r "[REM] Uninstalling Raytracer Driver from $(INSTALLDIR)lib/"
	@rm -f $(INSTALLDIR)lib/libRaytracerDriver.so

clean:
	@$(ECHO) -b "[CLN] PMD Localize"
	@$(ECHO) -b "[CLN] Raytracer Driver"
	@rm -f $(OBJ)*.o
	@rm -f $(OBJ)*.so

$(OBJ)libPMDlocalize.so: $(OBJ)Logger.o $(OBJ)PMDLocalizationDriver.o $(OBJ)CameraParameters.o $(OBJ)Raytracer.o $(OBJ)CGALRaytracer.o $(OBJ)ICP.o
	@$(ECHO) -y "[LNK] Linking PMD Localize Library"
	@$(CPP) $(CFLAGS) $(PKG_CONFIG) -o $(OBJ)libPMDlocalize.so -shared -fPIC -lm $(OBJ)Logger.o $(OBJ)PMDLocalizationDriver.o $(OBJ)Raytracer.o $(OBJ)CameraParameters.o $(OBJ)CGALRaytracer.o $(OBJ)ICP.o -L$(INSTALLDIR)lib/ -lann -lnewmat -lmodel3dinterf -lCGAL

$(OBJ)libRaytracerDriver.so: $(OBJ)RaytracerDriver.o $(OBJ)CameraParameters.o $(OBJ)Raytracer.o $(OBJ)Bsp.o $(OBJ)CGALRaytracer.o
	@$(ECHO) -y "[LNK] Linking Raytracer Library"
	@$(CPP) $(CFLAGS) $(PKG_CONFIG) -o $(OBJ)libRaytracerDriver.so -shared -fPIC -lm $(OBJ)RaytracerDriver.o $(OBJ)Raytracer.o $(OBJ)Bsp.o $(OBJ)CameraParameters.o $(OBJ)CGALRaytracer.o -L$(INSTALLDIR)lib/ -lmodel3dinterf -lCGAL

$(OBJ): 
	@mkdir $@

$(OBJ)Logger.o: $(SRC)Logger.*
	@$(ECHO) -w "[CPP] Logger"
	@$(CPP) $(CFLAGS) -c -o $(OBJ)Logger.o $(SRC)Logger.cpp

$(OBJ)ICP.o: $(SRC)ICP.*
	@$(ECHO) -w "[CPP] ICP"
	@$(CPP) $(CFLAGS) -c -o $(OBJ)ICP.o $(SRC)ICP.cpp

$(OBJ)Bsp.o: $(SRC)Bsp.* 
	@$(ECHO) -w "[CPP] BSP Tree"
	@$(CPP) $(CFLAGS) -c -o $(OBJ)Bsp.o $(SRC)Bsp.cpp 

$(OBJ)Raytracer.o: $(SRC)Raytracer.* $(SRC)MatrixMath.hpp
	@$(ECHO) -w "[CPP] Raytracer"
	@$(CPP) $(CFLAGS) -c -o $(OBJ)Raytracer.o $(SRC)Raytracer.cpp

$(OBJ)CGALRaytracer.o: $(SRC)CGALRaytracer.*
	@$(ECHO) -w "[CPP] CGAL Raytracer"
	@$(CPP) $(CFLAGS) -c -o $(OBJ)CGALRaytracer.o $(SRC)CGALRaytracer.cpp -frounding-math

$(OBJ)RaytracerDriver.o: $(SRC)RaytracerDriver.*
	@echo "Compiling Raytracer driver..."
	@$(CPP) $(CFLAGS) -c -o $(OBJ)RaytracerDriver.o $(SRC)RaytracerDriver.cpp

$(OBJ)CameraParameters.o: $(SRC)CameraParameters.*
	@$(ECHO) -w "[CPP] CameraParameters"
	@$(CPP) $(CFLAGS) -c -o $(OBJ)CameraParameters.o $(SRC)CameraParameters.cpp

$(OBJ)PMDLocalizationDriver.o: $(SRC)PMDLocalizationDriver.*
	@$(ECHO) -w "[CPP] PMD Localization Driver"
	@$(CPP) $(CFLAGS) -c -o $(OBJ)PMDLocalizationDriver.o $(SRC)PMDLocalizationDriver.cpp
